spring.application.name=products

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Ecommerce
#spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.repositories.type=auto
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.data.mongodb.uri=mongodb://localhost:27017/Ecommerce

spring.kafka.bootstrap-servers=http://localhost:9092
spring.kafka.consumer.group-id=product-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

server.port=8083