spring.application.name=ApiGateway

spring.cloud.gateway.routes[0].id=users
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/Search/**

spring.cloud.gateway.routes[1].id=auth
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[2].id=products
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/Products/**

spring.cloud.gateway.routes[3].id=merchants
spring.cloud.gateway.routes[3].uri=http://localhost:8083
spring.cloud.gateway.routes[3].predicates[0]=Path=/Merchant/**

spring.cloud.gateway.routes[4].id=cart
spring.cloud.gateway.routes[4].uri=http://localhost:8084
spring.cloud.gateway.routes[4].predicates[0]=Path=/Cart/**
spring.cloud.gateway.routes[4].filters[0]=CustomAuthFilter

spring.cloud.gateway.routes[5].id=orders
spring.cloud.gateway.routes[5].uri=http://localhost:8085
spring.cloud.gateway.routes[5].predicates[0]=Path=/Orders/**
spring.cloud.gateway.routes[5].filters[0]=CustomAuthFilter

server.address=0.0.0.0
server.port=8080