spring.application.name=cart

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Ecommerce
#spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.repositories.type=auto
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.data.mongodb.uri=mongodb://localhost:27017/Ecommerce

server.port = 8084